"""
Static enrichment data for country pages:
 - GEOGRAPHICAL_FEATURES  : highest peak, longest river, coastline, terrain, climate
 - COUNTRY_FACTS          : 4-5 interesting/fun facts per country
 - CURRENCY_CODES         : ISO 4217 code → { name, symbol } mapping (for the exchange page)
"""

# ─────────────────────────────────────────────
# Geographical Features
# highest_peak : (name, elevation_m)
# ─────────────────────────────────────────────
GEOGRAPHICAL_FEATURES = {
    "Afghanistan": {
        "highest_peak": ("Noshaq", 7492),
        "longest_river": "Amu Darya",
        "coastline_km": 0,
        "terrain": "Mostly rugged mountains; plains in north and southwest",
        "climate": "Arid to semi-arid; cold winters, hot summers",
        "natural_resources": "Natural gas, petroleum, coal, copper, chromite, talc, barites, sulfur, lead, zinc, iron ore, salt, precious and semiprecious stones",
    },
    "Albania": {
        "highest_peak": ("Korab", 2764),
        "longest_river": "Drin",
        "coastline_km": 362,
        "terrain": "Mostly mountains and hills; small plains along coast",
        "climate": "Mild temperate; cool, cloudy, wet winters; hot, clear, dry summers",
        "natural_resources": "Petroleum, natural gas, coal, bauxite, chromite, copper, iron ore, nickel, salt, timber, hydropower",
    },
    "Algeria": {
        "highest_peak": ("Tahat", 2908),
        "longest_river": "Chelif",
        "coastline_km": 998,
        "terrain": "Mostly high plateau and desert; some mountains; narrow, discontinuous coastal plain",
        "climate": "Arid to semi-arid; mild wet winters with hot dry summers along coast",
        "natural_resources": "Petroleum, natural gas, iron ore, phosphates, uranium, lead, zinc",
    },
    "Argentina": {
        "highest_peak": ("Aconcagua", 6962),
        "longest_river": "Paraná",
        "coastline_km": 4989,
        "terrain": "Rich plains of the Pampas in northern half, flat to rolling plateau of Patagonia in south, rugged Andes along western border",
        "climate": "Mostly temperate; arid in southeast; sub-Antarctic in southwest",
        "natural_resources": "Fertile plains of the pampas, lead, zinc, tin, copper, iron ore, manganese, petroleum, uranium, arable land",
    },
    "Australia": {
        "highest_peak": ("Mount Kosciuszko", 2228),
        "longest_river": "Murray",
        "coastline_km": 25760,
        "terrain": "Mostly low plateau with deserts; fertile plain in southeast",
        "climate": "Generally arid to semi-arid; temperate in south and east; tropical in north",
        "natural_resources": "Bauxite, coal, iron ore, copper, tin, gold, silver, uranium, nickel, tungsten, rare earth elements, mineral sands, lead, zinc, diamonds, natural gas, petroleum",
    },
    "Austria": {
        "highest_peak": ("Grossglockner", 3798),
        "longest_river": "Danube",
        "coastline_km": 0,
        "terrain": "Mostly mountains with Alps in west and south; mostly flat, with gentle slopes along eastern and northern margins",
        "climate": "Temperate; continental, cloudy; cold winters with frequent rain and some snow in lowlands, snow in mountains",
        "natural_resources": "Oil, coal, lignite, timber, iron ore, copper, zinc, antimony, magnesite, tungsten, graphite, salt, hydropower",
    },
    "Bangladesh": {
        "highest_peak": ("Saka Haphong", 1052),
        "longest_river": "Brahmaputra",
        "coastline_km": 580,
        "terrain": "Mostly flat alluvial plain; hilly in southeast",
        "climate": "Tropical; mild winter (October–March); hot, humid summer (March–June); humid, warm rainy monsoon (June–October)",
        "natural_resources": "Natural gas, arable land, timber, coal",
    },
    "Belgium": {
        "highest_peak": ("Signal de Botrange", 694),
        "longest_river": "Meuse",
        "coastline_km": 66,
        "terrain": "Flat coastal plains in northwest, central rolling hills, rugged mountains of Ardennes Forest in southeast",
        "climate": "Temperate; mild winters, cool summers; rainy, humid, cloudy",
        "natural_resources": "Construction materials, silica sand, carbonates",
    },
    "Bolivia": {
        "highest_peak": ("Nevado Sajama", 6542),
        "longest_river": "Bolivian Madeira",
        "coastline_km": 0,
        "terrain": "Rugged Andes Mountains with a highland plateau (Altiplano), hills, lowland plains of the Amazon Basin",
        "climate": "Varies with altitude; humid and tropical to cold and semi-arid",
        "natural_resources": "Tin, natural gas, petroleum, zinc, tungsten, antimony, silver, iron, lead, gold, timber, hydropower",
    },
    "Brazil": {
        "highest_peak": ("Pico da Neblina", 2994),
        "longest_river": "Amazon",
        "coastline_km": 7491,
        "terrain": "Mostly flat to rolling lowlands in north; some plains, hills, mountains, and narrow coastal belt",
        "climate": "Mostly tropical, but temperate in south",
        "natural_resources": "Bauxite, gold, iron ore, manganese, nickel, phosphates, platinum, tin, rare earth elements, uranium, petroleum, hydropower, timber",
    },
    "Canada": {
        "highest_peak": ("Mount Logan", 5959),
        "longest_river": "Mackenzie",
        "coastline_km": 202080,
        "terrain": "Mostly plains with mountains in west, lowlands in southeast",
        "climate": "Varies from temperate in south to subarctic and arctic in north",
        "natural_resources": "Iron ore, nickel, zinc, copper, gold, lead, rare earth elements, molybdenum, potash, diamonds, silver, fish, timber, wildlife, coal, petroleum, natural gas, hydropower",
    },
    "Chile": {
        "highest_peak": ("Nevado Ojos del Salado", 6893),
        "longest_river": "Loa",
        "coastline_km": 6435,
        "terrain": "Low coastal mountains; fertile central valley; rugged Andes in east",
        "climate": "Temperate; desert in north; Mediterranean in central region; cool and damp in south",
        "natural_resources": "Copper, timber, iron ore, nitrates, precious metals, molybdenum, hydropower",
    },
    "China": {
        "highest_peak": ("Mount Everest (Qomolangma)", 8848),
        "longest_river": "Yangtze",
        "coastline_km": 14500,
        "terrain": "Mostly mountains, high plateaus, deserts in west; plains, deltas, and hills in east",
        "climate": "Extremely diverse; tropical in south to subarctic in north",
        "natural_resources": "Coal, iron ore, helium, natural gas, mercury, tin, tungsten, antimony, manganese, molybdenum, vanadium, magnetite, aluminum, lead, zinc, rare earth elements, uranium, hydropower potential (world's largest)",
    },
    "Colombia": {
        "highest_peak": ("Pico Cristóbal Colón", 5775),
        "longest_river": "Magdalena",
        "coastline_km": 3208,
        "terrain": "Flat coastal lowlands, central highlands, high Andes Mountains, eastern lowland plains (Llanos)",
        "climate": "Tropical along coast and eastern plains; cooler in highlands",
        "natural_resources": "Petroleum, natural gas, coal, iron ore, nickel, gold, copper, emeralds, hydropower",
    },
    "Democratic Republic Of The Congo": {
        "highest_peak": ("Margherita Peak", 5110),
        "longest_river": "Congo",
        "coastline_km": 37,
        "terrain": "Vast central basin is a low-lying plateau; mountains in east",
        "climate": "Tropical; hot and humid in equatorial river basin; cooler and drier in southern highlands",
        "natural_resources": "Cobalt, copper, niobium, tantalum, petroleum, industrial and gem diamonds, gold, silver, zinc, manganese, tin, uranium, coal, hydropower, timber",
    },
    "Denmark": {
        "highest_peak": ("Møllehøj", 171),
        "longest_river": "Gudenå",
        "coastline_km": 7314,
        "terrain": "Low and flat to gently rolling plains",
        "climate": "Temperate; humid and overcast; mild windy winters and cool summers",
        "natural_resources": "Petroleum, natural gas, fish, arable land, salt, limestone, chalk, stone, gravel and sand",
    },
    "Egypt": {
        "highest_peak": ("Mount Catherine", 2629),
        "longest_river": "Nile",
        "coastline_km": 2450,
        "terrain": "Vast desert plateau interrupted by Nile valley and delta",
        "climate": "Desert; hot, dry summers with moderate winters",
        "natural_resources": "Petroleum, natural gas, iron ore, phosphates, manganese, limestone, gypsum, talc, asbestos, lead, rare earth elements, zinc",
    },
    "Ethiopia": {
        "highest_peak": ("Ras Dejen", 4550),
        "longest_river": "Blue Nile",
        "coastline_km": 0,
        "terrain": "High plateau with central mountain range divided by Great Rift Valley",
        "climate": "Tropical monsoon with wide topographic-induced variation",
        "natural_resources": "Small reserves of gold, platinum, copper, potash, natural gas, hydropower",
    },
    "France": {
        "highest_peak": ("Mont Blanc", 4808),
        "longest_river": "Loire",
        "coastline_km": 3427,
        "terrain": "Mostly flat plains or gently rolling hills in north and west; remainder is mountainous, especially Pyrenees in south, Alps in east",
        "climate": "Generally cool winters and mild summers, but mild winters and hot summers along the Mediterranean; occasional strong, cold, dry, north-to-northwesterly wind known as the mistral",
        "natural_resources": "Coal, iron ore, bauxite, zinc, uranium, antimony, arsenic, potash, feldspar, fluorspar, gypsum, timber, fish, gold",
    },
    "Germany": {
        "highest_peak": ("Zugspitze", 2962),
        "longest_river": "Rhine",
        "coastline_km": 2389,
        "terrain": "Lowlands in north, uplands in center, Bavarian Alps in south",
        "climate": "Temperate and marine; cool, cloudy, wet winters and summers; occasional warm mountain (foehn) wind",
        "natural_resources": "Coal, lignite, natural gas, iron ore, copper, nickel, uranium, potash, salt, construction materials, timber, arable land",
    },
    "Ghana": {
        "highest_peak": ("Mount Afadjato", 885),
        "longest_river": "Volta",
        "coastline_km": 539,
        "terrain": "Mostly low plains with dissected plateau in south-central area",
        "climate": "Tropical; warm and comparatively dry along southeast coast; hot and humid in southwest; hot and dry in north",
        "natural_resources": "Gold, timber, industrial diamonds, bauxite, manganese, fish, rubber, hydropower, petroleum, silver, salt, limestone",
    },
    "Greece": {
        "highest_peak": ("Mount Olympus", 2917),
        "longest_river": "Alibakiotis",
        "coastline_km": 13676,
        "terrain": "Mostly mountains with ranges extending into the sea as peninsulas or chains of islands",
        "climate": "Temperate; mild wet winters; hot dry summers",
        "natural_resources": "Lignite, petroleum, iron ore, bauxite, lead, zinc, nickel, magnesite, marble, salt, hydropower potential",
    },
    "Iceland": {
        "highest_peak": ("Hvannadalshnúkur", 2110),
        "longest_river": "Þjórsá",
        "coastline_km": 4970,
        "terrain": "Mostly plateau interspersed with mountain peaks, icefields; coast deeply indented by bays and fiords",
        "climate": "Temperate; moderated by North Atlantic Current; mild windy winters; damp cool summers",
        "natural_resources": "Fish, hydropower, geothermal power, diatomite",
    },
    "India": {
        "highest_peak": ("Kangchenjunga", 8586),
        "longest_river": "Ganga (Ganges)",
        "coastline_km": 7516,
        "terrain": "Upland plain (Deccan Plateau) in south, flat to rolling plain along the Ganges, deserts in west, Himalayas in north",
        "climate": "Varies from tropical monsoon in south to temperate in north",
        "natural_resources": "Coal, iron ore, manganese, mica, bauxite, rare earth elements, titanium ore, chromite, natural gas, diamonds, petroleum, limestone, arable land",
    },
    "Indonesia": {
        "highest_peak": ("Puncak Jaya", 4884),
        "longest_river": "Kapuas",
        "coastline_km": 54716,
        "terrain": "Mostly coastal lowlands; larger islands have interior mountains",
        "climate": "Tropical; hot, humid; more moderate in highlands",
        "natural_resources": "Petroleum, tin, natural gas, nickel, timber, bauxite, copper, fertile soils, coal, gold, silver",
    },
    "Iran": {
        "highest_peak": ("Damavand", 5610),
        "longest_river": "Karun",
        "coastline_km": 2440,
        "terrain": "Rugged, mountainous rim; high, central basin with deserts, mountains; small, discontinuous plains along both coasts",
        "climate": "Mostly arid or semi-arid, subtropical along Caspian coast",
        "natural_resources": "Petroleum, natural gas, coal, chromium, copper, iron ore, lead, manganese, zinc, sulfur",
    },
    "Iraq": {
        "highest_peak": ("Cheekha Dar", 3611),
        "longest_river": "Euphrates",
        "coastline_km": 58,
        "terrain": "Mostly broad plains; reedy marshes along Iranian border in south with large flooded areas; mountains along borders with Iran and Turkey",
        "climate": "Mostly desert; mild to cool winters with dry, hot, cloudless summers; northern mountainous regions along Iranian and Turkish borders experience cold winters",
        "natural_resources": "Petroleum, natural gas, phosphates, sulfur",
    },
    "Italy": {
        "highest_peak": ("Mont Blanc (Monte Bianco)", 4808),
        "longest_river": "Po",
        "coastline_km": 7600,
        "terrain": "Mostly rugged and mountainous; some plains, coastal lowlands",
        "climate": "Predominantly Mediterranean; alpine in far north; hot and dry in south",
        "natural_resources": "Coal, antimony, mercury, zinc, potash, marble, barite, asbestos, pumice, fluorspar, feldspar, pyrite, natural gas and crude oil reserves, fish, arable land",
    },
    "Japan": {
        "highest_peak": ("Mount Fuji", 3776),
        "longest_river": "Shinano",
        "coastline_km": 29751,
        "terrain": "Mostly rugged and mountainous",
        "climate": "Varies from tropical in south to cool temperate in north",
        "natural_resources": "Negligible mineral resources, fish; note: with virtually no natural energy resources, Japan is the world's largest importer of coal and liquefied natural gas, as well as the second largest importer of oil",
    },
    "Kenya": {
        "highest_peak": ("Mount Kenya", 5199),
        "longest_river": "Tana",
        "coastline_km": 536,
        "terrain": "Low plains rise to central highlands bisected by Great Rift Valley; fertile plateau in west",
        "climate": "Varies from tropical along coast to arid in interior",
        "natural_resources": "Limestone, soda ash, salt, gemstones, fluorspar, zinc, diatomite, gypsum, wildlife, hydropower",
    },
    "Mexico": {
        "highest_peak": ("Pico de Orizaba", 5636),
        "longest_river": "Río Grande",
        "coastline_km": 9330,
        "terrain": "High, rugged mountains; low coastal plains; high plateaus; desert",
        "climate": "Varies from tropical to desert",
        "natural_resources": "Petroleum, silver, copper, gold, lead, zinc, natural gas, timber",
    },
    "Nepal": {
        "highest_peak": ("Mount Everest", 8848),
        "longest_river": "Koshi",
        "coastline_km": 0,
        "terrain": "Terai or flat river plain of the Ganges in south, central hill region with rugged Himalayas in north",
        "climate": "Varies from cool summers and severe winters in north to subtropical summers and mild winters in south",
        "natural_resources": "Quartz, water, timber, hydropower, scenic beauty, small deposits of lignite, copper, cobalt, iron ore",
    },
    "Netherlands": {
        "highest_peak": ("Mount Scenery", 862),
        "longest_river": "Rhine",
        "coastline_km": 451,
        "terrain": "Mostly coastal lowland and reclaimed land (polders); some hills in southeast",
        "climate": "Temperate; marine; cool summers and mild winters",
        "natural_resources": "Natural gas, petroleum, peat, limestone, salt, sand and gravel, arable land",
    },
    "New Zealand": {
        "highest_peak": ("Aoraki / Mount Cook", 3724),
        "longest_river": "Waikato",
        "coastline_km": 15134,
        "terrain": "Predominately mountainous with some large coastal plains",
        "climate": "Temperate with sharp regional contrasts",
        "natural_resources": "Natural gas, iron ore, sand, coal, timber, hydropower, gold, limestone",
    },
    "Nigeria": {
        "highest_peak": ("Chappal Waddi", 2419),
        "longest_river": "Niger",
        "coastline_km": 853,
        "terrain": "Southern lowlands merge into central hills and plateaus; mountains in southeast, plains in north",
        "climate": "Varies; equatorial in south, tropical in center, arid in north",
        "natural_resources": "Natural gas, petroleum, tin, iron ore, coal, limestone, niobium, lead, zinc, arable land",
    },
    "Norway": {
        "highest_peak": ("Galdhøpiggen", 2469),
        "longest_river": "Glomma",
        "coastline_km": 25148,
        "terrain": "Glaciated; mostly high plateaus and rugged mountains broken by fertile valleys; small, scattered plains; coastline deeply indented by fjords; arctic tundra in north",
        "climate": "Temperate along coast, modified by North Atlantic Current; colder interior with increased precipitation and colder summers; rainy year-round on west coast",
        "natural_resources": "Petroleum, natural gas, iron ore, copper, lead, zinc, titanium, pyrites, nickel, fish, timber, hydropower",
    },
    "Pakistan": {
        "highest_peak": ("K2", 8611),
        "longest_river": "Indus",
        "coastline_km": 1046,
        "terrain": "Flat Indus plain in east; mountains in north and northwest; Balochistan plateau in west",
        "climate": "Mostly hot, dry desert; temperate in northwest; arctic in north",
        "natural_resources": "Arable land, extensive natural gas reserves, limited petroleum, poor quality coal, iron ore, copper, salt, limestone",
    },
    "Peru": {
        "highest_peak": ("Huascarán", 6768),
        "longest_river": "Amazon",
        "coastline_km": 2414,
        "terrain": "Western coastal plain (costa), high and rugged Andes in center (sierra), eastern lowland jungle of Amazon Basin (selva)",
        "climate": "Varies from tropical in east to dry desert in west; temperate to frigid in Andes",
        "natural_resources": "Copper, silver, gold, petroleum, timber, fish, iron ore, coal, phosphate, potash, hydropower, natural gas",
    },
    "Philippines": {
        "highest_peak": ("Mount Apo", 2954),
        "longest_river": "Cagayan",
        "coastline_km": 36289,
        "terrain": "Mostly mountains with narrow to extensive coastal lowlands",
        "climate": "Tropical marine; northeast monsoon (November to April); southwest monsoon (May to October)",
        "natural_resources": "Timber, petroleum, nickel, cobalt, silver, gold, salt, copper",
    },
    "Poland": {
        "highest_peak": ("Rysy", 2499),
        "longest_river": "Vistula",
        "coastline_km": 491,
        "terrain": "Mostly flat plain; mountains along southern border",
        "climate": "Temperate with cold, cloudy, moderately severe winters with frequent precipitation; mild summers with frequent showers and thunderstorms",
        "natural_resources": "Coal, sulfur, copper, natural gas, silver, lead, salt, amber, arable land",
    },
    "Portugal": {
        "highest_peak": ("Ponta do Pico", 2351),
        "longest_river": "Tagus (Tejo)",
        "coastline_km": 1793,
        "terrain": "Mountainous north of the Tagus River, rolling plains in the south",
        "climate": "Maritime temperate; cool and rainy in north, warmer and drier in south",
        "natural_resources": "Fish, forests (cork), iron ore, copper, zinc, tin, tungsten, silver, gold, uranium, marble, clay, gypsum, salt, arable land, hydropower",
    },
    "Russia": {
        "highest_peak": ("Elbrus", 5642),
        "longest_river": "Ob–Irtysh",
        "coastline_km": 37653,
        "terrain": "Broad plain with low hills west of Urals; vast coniferous forest and tundra in Siberia; uplands and mountains along southern border regions",
        "climate": "Ranges from steppes in the south through humid continental in much of European Russia, subarctic in Siberia to tundra climate in the polar north; winters vary from cool along Black Sea coast to frigid in Siberia",
        "natural_resources": "Vast natural resources including major deposits of oil, natural gas, coal, and many strategic minerals, bauxite, reserves of rare earth elements, timber",
    },
    "Saudi Arabia": {
        "highest_peak": ("Jabal Sawda", 3133),
        "longest_river": "No permanent rivers",
        "coastline_km": 2640,
        "terrain": "Mostly sandy desert",
        "climate": "Harsh, dry desert with great temperature extremes",
        "natural_resources": "Petroleum, natural gas, iron ore, gold, copper",
    },
    "South Africa": {
        "highest_peak": ("Injasuti", 3450),
        "longest_river": "Orange",
        "coastline_km": 2798,
        "terrain": "Vast interior plateau rimmed by rugged hills and narrow coastal plain",
        "climate": "Mostly semi-arid; subtropical along east coast; sunny days, cool nights",
        "natural_resources": "Gold, chromium, antimony, coal, iron ore, manganese, nickel, phosphates, tin, rare earth elements, uranium, gem diamonds, platinum, copper, vanadium, salt, natural gas",
    },
    "South Korea": {
        "highest_peak": ("Hallasan", 1950),
        "longest_river": "Nakdong",
        "coastline_km": 2413,
        "terrain": "Mostly hills and mountains; wide coastal plains in west and south",
        "climate": "Temperate, with rainfall heavier in summer than winter; cold winters",
        "natural_resources": "Coal, tungsten, graphite, molybdenum, lead, hydropower potential",
    },
    "Spain": {
        "highest_peak": ("Teide (Tenerife)", 3718),
        "longest_river": "Tagus (Tajo)",
        "coastline_km": 4964,
        "terrain": "Large, flat to dissected plateau surrounded by rugged hills; Pyrenees in north",
        "climate": "Temperate; clear, hot summers in interior, more moderate and cloudy along coast; cloudy, cold winters in interior, partly cloudy and cool along coast",
        "natural_resources": "Coal, lignite, iron ore, copper, lead, zinc, uranium, tungsten, mercury, pyrites, magnesite, fluorspar, gypsum, sepiolite, kaolin, potash, hydropower, arable land",
    },
    "Sweden": {
        "highest_peak": ("Kebnekaise", 2104),
        "longest_river": "Klarälven–Göta älv",
        "coastline_km": 3218,
        "terrain": "Mostly flat or gently rolling lowlands; mountains in west",
        "climate": "Temperate in south with cold, cloudy winters and cool, partly cloudy summers; subarctic in north",
        "natural_resources": "Iron ore, copper, lead, zinc, gold, silver, tungsten, uranium, arsenic, feldspar, timber, hydropower",
    },
    "Switzerland": {
        "highest_peak": ("Dufourspitze", 4634),
        "longest_river": "Rhine",
        "coastline_km": 0,
        "terrain": "Mostly mountains (Alps in south, Jura in northwest) with a central plateau of rolling hills, plains, and large lakes",
        "climate": "Temperate, but varies with altitude; cold, cloudy, rainy/snowy winters; cool to warm, cloudy, humid summers with occasional showers",
        "natural_resources": "Hydropower potential, timber, salt",
    },
    "Thailand": {
        "highest_peak": ("Doi Inthanon", 2565),
        "longest_river": "Mekong",
        "coastline_km": 3219,
        "terrain": "Central plain; Khorat Plateau in the east; mountains elsewhere",
        "climate": "Tropical; rainy, warm, cloudy southwest monsoon (mid-May to September); dry, cool northeast monsoon (November to mid-March); southern isthmus always hot and humid",
        "natural_resources": "Tin, rubber, natural gas, tungsten, tantalum, timber, lead, fish, gypsum, lignite, fluorite, arable land",
    },
    "Turkey": {
        "highest_peak": ("Mount Ararat", 5137),
        "longest_river": "Kızılırmak",
        "coastline_km": 7200,
        "terrain": "High central plateau (Anatolia); narrow coastal plain; several mountain ranges",
        "climate": "Temperate; hot, dry summers with mild, wet winters; harsher in interior",
        "natural_resources": "Coal, iron ore, copper, chromium, antimony, mercury, gold, barite, borate, celestite (strontium), emery, feldspar, limestone, magnesite, marble, perlite, pumice, pyrites (sulfur), clay, arable land, hydropower",
    },
    "Ukraine": {
        "highest_peak": ("Hoverla", 2061),
        "longest_river": "Dnieper",
        "coastline_km": 2782,
        "terrain": "Most of Ukraine consists of fertile plains (steppes) and plateaus, mountains being found only in the west (the Carpathians) and in the Crimean Peninsula in the extreme south",
        "climate": "Temperate continental; Mediterranean only on the southern Crimean coast; precipitation disproportionately distributed, highest in west and north, lesser in east and southeast; winters vary from cool along the Black Sea to cold farther inland",
        "natural_resources": "Iron ore, coal, manganese, natural gas, oil, salt, sulfur, graphite, titanium, magnesium, kaolin, nickel, mercury, timber, arable land",
    },
    "United Kingdom": {
        "highest_peak": ("Ben Nevis", 1345),
        "longest_river": "Severn",
        "coastline_km": 12429,
        "terrain": "Mostly rugged hills and low mountains; level to rolling plains in east and southeast",
        "climate": "Temperate; moderated by prevailing southwest winds over the North Atlantic Current; more than one-half of the days are overcast",
        "natural_resources": "Coal, petroleum, natural gas, iron ore, lead, zinc, gold, tin, limestone, salt, clay, chalk, gypsum, potash, silica sand, slate, arable land",
    },
    "United States": {
        "highest_peak": ("Denali (Mount McKinley)", 6190),
        "longest_river": "Missouri",
        "coastline_km": 19924,
        "terrain": "Vast central plain, mountains in west, hills and low mountains in east; rugged mountains and broad river valleys in Alaska; rugged, volcanic topography in Hawaii",
        "climate": "Mostly temperate, but tropical in Hawaii and Florida, arctic in Alaska, semi-arid in the great plains west of the Mississippi River, and arid in the Great Basin of the southwest",
        "natural_resources": "Coal, copper, lead, molybdenum, phosphates, rare earth elements, uranium, bauxite, gold, iron, mercury, nickel, potash, silver, tungsten, zinc, petroleum, natural gas, timber, arable land",
    },
    "Venezuela": {
        "highest_peak": ("Pico Bolívar", 4978),
        "longest_river": "Orinoco",
        "coastline_km": 2800,
        "terrain": "Andes Mountains and Maracaibo Lowlands in northwest; central plains (llanos); Guiana Highlands in southeast",
        "climate": "Tropical; hot, humid; more moderate in highlands",
        "natural_resources": "Petroleum, natural gas, iron ore, gold, bauxite, other minerals, hydropower, diamonds",
    },
    "Vietnam": {
        "highest_peak": ("Fansipan", 3143),
        "longest_river": "Mekong",
        "coastline_km": 3444,
        "terrain": "Low, flat delta in south and north; central highlands; hilly, mountainous in far north and northwest",
        "climate": "Tropical in south; monsoonal in north with hot, rainy season (May to September) and warm, dry season (October to March)",
        "natural_resources": "Phosphates, coal, manganese, rare earth elements, bauxite, chromate, offshore oil and gas deposits, timber, hydropower, arable land",
    },
}


# ─────────────────────────────────────────────
# Interesting / Fun Facts
# ─────────────────────────────────────────────
COUNTRY_FACTS = {
    "Afghanistan": [
        "Afghanistan is home to the ancient Silk Road, a network of trade routes connecting China to the Mediterranean.",
        "The country has one of the youngest populations in the world, with nearly 60% under 25 years old.",
        "Afghan rugs and carpets are world-famous and considered some of the finest handmade textiles.",
        "The Buddhas of Bamiyan, two 6th-century statues, were the tallest standing Buddha statues in the world before being destroyed in 2001.",
    ],
    "Albania": [
        "Albania is one of the few countries where nodding your head means 'no' and shaking it means 'yes'.",
        "Mother Teresa was of Albanian heritage, born to Albanian parents in Skopje.",
        "Albania has more bunkers per square kilometre than any other country — nearly 750,000 built during the communist era.",
        "The Albanian national symbol, the double-headed eagle, is one of the oldest national symbols in the world.",
    ],
    "Algeria": [
        "Algeria is the largest country in Africa by area.",
        "About 90% of Algeria is covered by the Sahara Desert.",
        "Algeria has the largest oil and gas reserves in Africa.",
        "The ancient city of Timgad, built by the Romans in 100 AD, is remarkably preserved and located in Algeria.",
    ],
    "Argentina": [
        "Argentina is the 2nd largest country in South America and 8th in the world.",
        "Argentina has more psychoanalysts per capita than any other country in the world.",
        "The tango originated in the working-class neighborhoods of Buenos Aires.",
        "Argentina was the first country in Latin America to legalize same-sex marriage (2010).",
        "Patagonia, shared with Chile, is home to some of the world's largest glaciers.",
    ],
    "Australia": [
        "Australia is the only country that is also a continent.",
        "Australia has more kangaroos than people (approximately 2:1 ratio).",
        "The Great Barrier Reef is the world's largest coral reef system, visible from space.",
        "Australia was the second country in the world to give women the right to vote (1902).",
        "The box jellyfish found in Australian waters is considered the most venomous marine animal in the world.",
    ],
    "Austria": [
        "Austria gave the world famous composers like Mozart, Haydn, Schubert, and Strauss.",
        "The Vienna Philharmonic is one of the oldest orchestras in the world.",
        "Austria's Hallstatt village gave its name to the Hallstatt period of the European Iron Age.",
        "The word 'Austria' comes from 'Ostarrichi', meaning 'Eastern Realm'.",
    ],
    "Bangladesh": [
        "Bangladesh is one of the most densely populated countries in the world.",
        "The Sundarbans, shared with India, is the world's largest mangrove forest.",
        "Bangladesh is the birthplace of microcredit, pioneered by Nobel Laureate Muhammad Yunus.",
        "Over half the world's jute is produced in Bangladesh.",
    ],
    "Belgium": [
        "Belgium produces over 220,000 tonnes of chocolate per year and is considered the chocolate capital of the world.",
        "French fries (pommes frites) were invented in Belgium, not France.",
        "Belgium is home to NATO headquarters and the European Union's main administrative offices.",
        "Belgium has three official languages: Dutch, French, and German.",
    ],
    "Bolivia": [
        "Bolivia has two capitals: Sucre (constitutional) and La Paz (government seat), making it one of the few countries with two capitals.",
        "Lake Titicaca is the world's highest navigable lake, shared between Bolivia and Peru.",
        "Bolivia's Salar de Uyuni is the world's largest salt flat, covering over 10,000 km².",
        "Bolivia is one of only two landlocked countries in South America.",
    ],
    "Brazil": [
        "Brazil is the largest country in South America and the 5th largest in the world.",
        "The Amazon Rainforest, mostly in Brazil, is the world's largest tropical rainforest and produces 20% of the world's oxygen.",
        "Brazil is the only Portuguese-speaking country in the Americas.",
        "Brazil has won the FIFA World Cup a record 5 times.",
        "Brazil is home to the world's largest carnival celebration in Rio de Janeiro.",
    ],
    "Canada": [
        "Canada has the world's longest coastline, stretching 202,080 km.",
        "Canada has more lakes than any other country, containing 60% of the world's fresh lake water.",
        "The CN Tower in Toronto was the tallest free-standing structure in the world from 1975 to 2007.",
        "Basketball was invented by Canadian James Naismith in 1891.",
        "Canada produces about 71% of the world's maple syrup.",
    ],
    "Chile": [
        "Chile is the longest country in the world, stretching 4,300 km from north to south.",
        "The Atacama Desert in Chile is the driest non-polar desert on Earth.",
        "Chile has the largest copper reserves in the world.",
        "The Andes Mountains run the entire length of Chile.",
        "Easter Island (Rapa Nui), famous for its giant stone statues (moai), belongs to Chile.",
    ],
    "China": [
        "China is home to the world's oldest continuous civilization, dating back over 5,000 years.",
        "China invented paper, printing, gunpowder, and the compass — the four great inventions of the ancient world.",
        "The Great Wall of China stretches approximately 21,196 km.",
        "China is the world's most populous country and the second-largest economy.",
        "China is the world's largest producer and consumer of pork.",
    ],
    "Colombia": [
        "Colombia is the only country in South America with coasts on both the Pacific Ocean and the Caribbean Sea.",
        "Colombia is the world's largest producer of emeralds, supplying 70–90% of the world's supply.",
        "Colombia is the second most biodiverse country in the world.",
        "The Magdalena River is Colombia's main river and was a lifeline for civilization in the region.",
    ],
    "Denmark": [
        "Denmark is consistently ranked as one of the happiest countries in the world.",
        "The Danish concept of 'hygge' (coziness and comfort) has influenced cultures worldwide.",
        "Denmark is the oldest kingdom in Europe, dating back to the 10th century.",
        "LEGO was invented in Denmark in 1932.",
        "Denmark's islands include Greenland, the world's largest island.",
    ],
    "Egypt": [
        "Egypt is home to one of the Seven Wonders of the Ancient World: the Great Pyramid of Giza.",
        "The Nile River, flowing through Egypt, is the longest river in the world.",
        "Ancient Egypt was one of the world's first major civilizations, dating back 5,000 years.",
        "The city of Alexandria was home to the Great Library of Alexandria, one of the largest libraries of the ancient world.",
        "Egypt has the world's third-most UNESCO World Heritage Sites.",
    ],
    "Ethiopia": [
        "Ethiopia is the oldest independent country in Africa and one of the oldest in the world.",
        "Coffee originated in Ethiopia and is named after the Kaffa region.",
        "Ethiopia runs on its own calendar which is 7–8 years behind the Gregorian calendar.",
        "Ethiopia has never been colonized (except briefly by Italy 1935–41).",
        "The source of the Blue Nile is in Ethiopia's Lake Tana.",
    ],
    "France": [
        "France is the most visited country in the world, attracting over 90 million tourists annually.",
        "The Eiffel Tower was originally intended to be a temporary structure for the 1889 World's Fair.",
        "France has the largest number of UNESCO World Heritage Sites in Europe.",
        "France is bordered by 11 different countries / territories — more than any other country.",
        "French cuisine was the first to be inscribed on UNESCO's list of Intangible Cultural Heritage.",
    ],
    "Germany": [
        "Germany invented the automobile and has some of the fastest speed limits in the world (on the Autobahn).",
        "Beer and bread are deeply embedded in German culture; Germany has over 1,500 different beers and 3,200 types of bread.",
        "Germany was the birthplace of the printing press, invented by Johannes Gutenberg around 1440.",
        "Germany has over 1,500 breweries and the world-famous Oktoberfest celebrates this tradition.",
        "Germany is the second most popular migration destination in the world after the US.",
    ],
    "Ghana": [
        "Ghana was the first sub-Saharan African country to gain independence from colonial rule (1957).",
        "Ghana is named after the ancient Ghana Empire, though modern Ghana is not geographically the same.",
        "Ghana is one of the world's largest producers of gold and cocoa.",
        "The Kente cloth, woven by the Ashanti people, is one of Africa's most recognizable textiles.",
    ],
    "Greece": [
        "Greece is considered the birthplace of Western civilization, democracy, and the Olympic Games.",
        "Greece has the longest coastline in Europe (13,676 km) and more than 6,000 islands.",
        "About 80% of Greece is mountainous.",
        "The Greek alphabet is the oldest alphabetic script still in use.",
        "Greece has the world's third-largest merchant shipping fleet.",
    ],
    "Iceland": [
        "Iceland is the world's oldest democracy, with its parliament (Alþingi) founded in 930 AD.",
        "Iceland has no army and is one of the most peaceful countries in the world.",
        "Iceland generates almost 100% of its electricity from renewable energy (hydropower and geothermal).",
        "The Northern Lights (Aurora Borealis) are visible in Iceland from September to April.",
        "Iceland has no mosquitoes due to its unique climate.",
    ],
    "India": [
        "India is the world's largest democracy by population.",
        "Chess was invented in India around the 6th century AD.",
        "India has the second-largest number of English speakers in the world after the USA.",
        "The Indian Space Research Organisation (ISRO) is the first Asian space agency to reach Mars orbit.",
        "Yoga, one of the world's most popular wellness practices, originated in India over 5,000 years ago.",
    ],
    "Indonesia": [
        "Indonesia is the world's largest archipelago, consisting of over 17,000 islands.",
        "Indonesia has the fourth-largest population in the world.",
        "Indonesia is one of the most biodiverse countries on Earth, home to the orangutan and Komodo dragon.",
        "Bali (part of Indonesia) is one of the world's most popular tourist destinations.",
        "Indonesia is the world's largest producer of palm oil.",
    ],
    "Iran": [
        "Iran (ancient Persia) is one of the world's oldest civilizations, dating back over 7,000 years.",
        "Iran has the world's second-largest natural gas reserves and fourth-largest proven oil reserves.",
        "Iranian carpets are among the finest in the world and have been exported for centuries.",
        "Iran is home to 26 UNESCO World Heritage Sites.",
        "The Persian poet Rumi is one of the best-selling poets in the United States.",
    ],
    "Italy": [
        "Italy has more UNESCO World Heritage Sites than any other country in the world (58).",
        "The Roman Empire was one of the most powerful empires in history, centered in modern-day Italy.",
        "Italy invented opera, the piano, and many other musical forms.",
        "Italy produces about 20% of the world's wine.",
        "The longest river in Italy, the Po, flows through the most fertile agricultural region.",
    ],
    "Japan": [
        "Japan is made up of over 6,800 islands.",
        "Japan has the world's oldest continuously operating company, Kongō Gumi, founded in 578 AD.",
        "Japan has the highest life expectancy in the world.",
        "Mount Fuji, Japan's highest peak, is considered a sacred symbol and has been painted and photographed more than any other mountain.",
        "Japan's high-speed bullet trains (Shinkansen) have an average delay of only 36 seconds.",
    ],
    "Kenya": [
        "Kenya has some of the world's best long-distance runners and has won over 100 Olympic medals in athletics.",
        "The Great Rift Valley runs through Kenya and is where some of the earliest human fossils were discovered.",
        "Kenya is home to the Maasai Mara, one of the world's greatest wildlife reserves.",
        "Nairobi is the only capital city in the world with a national park within its boundaries.",
    ],
    "Mexico": [
        "Mexico is the birthplace of chocolate, tomatoes, and corn (maiz).",
        "Mexico City is one of the largest cities in the world and was built on top of the ancient Aztec capital, Tenochtitlan.",
        "Mexico has the world's largest number of Spanish speakers.",
        "The ancient Mayan civilization, centered in Mexico, created one of the most sophisticated calendars in the ancient world.",
        "Mexico has 35 UNESCO World Heritage Sites.",
    ],
    "Nepal": [
        "Nepal has eight of the world's ten highest mountains, including Mount Everest, the world's highest peak.",
        "Nepal is the birthplace of Siddhartha Gautama (the Buddha).",
        "Nepal is the only country in the world with a non-rectangular national flag.",
        "Nepal is home to the snow leopard, one-horned rhinoceros, and red panda.",
    ],
    "Netherlands": [
        "The Netherlands is 26% below sea level, with an elaborate system of dikes protecting the land.",
        "The Netherlands is the world's second-largest exporter of food (after the USA).",
        "Dutch is one of only three Germanic languages with over 15 million native speakers.",
        "Cycling is the primary mode of transport in the Netherlands — there are more bikes than people.",
        "The Dutch Golden Age of painting produced masters like Rembrandt and Vermeer.",
    ],
    "New Zealand": [
        "New Zealand was the first country in the world to give women the right to vote (1893).",
        "New Zealand has more sheep than people — approximately 5 sheep per person.",
        "The kiwi, New Zealand's national bird, is the only bird with nostrils at the tip of its beak.",
        "New Zealand's Hobbiton, used in The Lord of the Rings films, is a major tourist attraction.",
        "New Zealand is one of the last land areas discovered and settled by humans (~1280 AD).",
    ],
    "Nigeria": [
        "Nigeria is the most populous country in Africa.",
        "Nigeria has the largest economy in Africa.",
        "Nigeria is home to over 500 languages and ethnic groups.",
        "Nollywood (the Nigerian film industry) is the second most prolific film industry in the world.",
        "Nigeria is one of the world's largest producers of crude oil.",
    ],
    "Norway": [
        "Norway consistently ranks as one of the world's richest and most liveable countries.",
        "Norway is home to some of the most spectacular fjords in the world.",
        "Norway was the birthplace of the sport of skiing.",
        "Norway has the world's longest road tunnel (24.5 km) — the Lærdal Tunnel.",
        "Norway pioneered the concept of the sovereign wealth fund (Government Pension Fund Global).",
    ],
    "Pakistan": [
        "Pakistan is home to K2, the world's second-highest mountain.",
        "Karachi, Pakistan's largest city, is one of the world's most populous cities.",
        "The Indus Valley Civilization, one of the earliest civilizations, flourished in what is now Pakistan.",
        "Pakistan has the world's second-largest salt mine (Khewra Salt Mine).",
    ],
    "Peru": [
        "Peru is home to Machu Picchu, one of the New Seven Wonders of the World.",
        "The Amazon River originates in Peru.",
        "Peru is the birthplace of the potato, which was cultivated here over 8,000 years ago.",
        "Lake Titicaca, shared with Bolivia, is the world's highest navigable lake.",
        "Peru has one of the highest concentrations of bird species in the world.",
    ],
    "Philippines": [
        "The Philippines is an archipelago of over 7,100 islands.",
        "The Philippines is the world's largest producer of coconuts.",
        "The tarsier, one of the world's smallest primates, is found in the Philippines.",
        "The Philippines has the world's longest underground river (Puerto Princesa, Palawan).",
    ],
    "Poland": [
        "Poland is where Marie Curie, the first woman to win a Nobel Prize, was born.",
        "Poland has never permanently disappeared from the world map despite being partitioned three times in the 18th century.",
        "Pierogi (dumplings) are one of Poland's most beloved national dishes.",
        "The Polish mathematician Nicolaus Copernicus proposed the heliocentric model of the solar system.",
    ],
    "Portugal": [
        "Portugal is the oldest nation-state in Europe, with borders established in 1143 AD.",
        "Portuguese is the 6th most spoken language in the world.",
        "Portugal was the first global maritime empire, establishing footholds across Africa, Asia, and the Americas.",
        "The Algarve region in southern Portugal is one of Europe's most popular tourist destinations.",
        "Port wine, one of the world's most famous fortified wines, originates from Portugal.",
    ],
    "Russia": [
        "Russia is the world's largest country by area, spanning 11 time zones.",
        "Lake Baikal in Russia is the world's deepest lake, containing about 20% of the world's surface fresh water.",
        "Russia launched the first human-made satellite (Sputnik) into space in 1957.",
        "The Trans-Siberian Railway is the longest railway line in the world (9,258 km).",
        "Russia has the world's largest forest (taiga), covering about 45% of its territory.",
    ],
    "Saudi Arabia": [
        "Saudi Arabia is the birthplace of Islam and home to Mecca and Medina, the two holiest cities in Islam.",
        "Saudi Arabia has the world's second-largest proven oil reserves.",
        "Saudi Arabia is the world's largest oil exporter.",
        "Until 2018, Saudi Arabia was the only country in the world that did not allow women to drive.",
        "Saudi Arabia has no permanent rivers or lakes.",
    ],
    "South Africa": [
        "South Africa is the only country to have voluntarily dismantled its nuclear weapons program.",
        "South Africa has 11 official languages — more than any other country.",
        "South Africa is the world's largest producer of platinum and chromium.",
        "South Africa hosted the FIFA World Cup in 2010, the first African country to do so.",
        "The Cradle of Humankind in South Africa is where some of the oldest known human fossils have been found.",
    ],
    "South Korea": [
        "South Korea has the fastest internet speed in the world.",
        "South Korea has the world's highest education rate, with nearly everyone completing high school.",
        "K-pop and Korean dramas (Hallyu / Korean Wave) have become global cultural phenomena.",
        "Samsung, LG, Hyundai, and Kia are all South Korean companies.",
        "South Korea went from one of the poorest countries to a high-income economy in just one generation.",
    ],
    "Spain": [
        "Spain is the second largest country in the European Union by area.",
        "The Running of the Bulls (San Fermín) in Pamplona is one of the world's most famous festivals.",
        "Spain is the world's biggest producer of olive oil.",
        "Flamenco, a passionate form of dance and music, originated in the Andalusian region of Spain.",
        "Spain has 50 UNESCO World Heritage Sites.",
    ],
    "Sweden": [
        "Sweden has won the most Nobel Prizes per capita of any country.",
        "Sweden is the birthplace of the adjustable wrench, the safety match, the three-point safety belt, and many other inventions.",
        "IKEA, Spotify, H&M, Volvo, and ABBA are all Swedish.",
        "Sweden has a 'freedom to roam' law (Allemansrätten) that allows anyone to walk, cycle, or camp on any land.",
        "Sweden hasn't been at war for over 200 years, making it one of the world's most long-standing neutral nations.",
    ],
    "Switzerland": [
        "Switzerland has not been at war since 1515, making it the longest neutrality in modern history.",
        "Swiss cheese and Swiss chocolate are among the most recognized food products in the world.",
        "Switzerland invented the World Wide Web through Tim Berners-Lee at CERN.",
        "Zurich consistently ranks as the world's most liveable city.",
        "Switzerland has four national languages: German, French, Italian, and Romansh.",
    ],
    "Thailand": [
        "Thailand was never formally colonized by a European power.",
        "Thailand is the world's largest exporter of rice.",
        "The Muay Thai martial art originated in Thailand.",
        "Thailand has the world's largest solid gold Buddha statue (Wat Traimit, Bangkok).",
        "Thai elephants are a national symbol and were once used in warfare.",
    ],
    "Turkey": [
        "Turkey is the only country in the world that straddles two continents — Europe and Asia.",
        "Istanbul (Constantinople) served as the capital of three great empires: Roman, Byzantine, and Ottoman.",
        "Turkey is home to the ancient city of Troy, famous from Homer's Iliad.",
        "Turkey is the world's largest producer of hazelnuts, meeting about 75% of global demand.",
        "The Tulip originated in Turkey and was introduced to the Netherlands in the 16th century.",
    ],
    "Ukraine": [
        "Ukraine is the largest country entirely within Europe by area.",
        "Ukraine is known as the 'breadbasket of Europe' due to its vast fertile farmlands.",
        "Chernobyl, site of the worst nuclear disaster in history (1986), is in Ukraine.",
        "The Ukrainian city of Odessa has one of the most famous staircases — the Potemkin Steps, made famous by the 1925 film 'Battleship Potemkin'.",
    ],
    "United Kingdom": [
        "The UK invented many of the world's most popular sports including football (soccer), cricket, rugby, tennis, and golf.",
        "The Royal Mail, established in 1516, is the world's oldest postal service still in operation.",
        "The UK was the first country to industrialize during the Industrial Revolution.",
        "The United Kingdom is home to the world's most visited museum — the British Museum.",
        "The English language, originating in England, is the most widely spoken language in the world.",
    ],
    "United States": [
        "The United States is the world's largest economy by nominal GDP.",
        "The US has won more Olympic Games medals than any other country in history.",
        "Silicon Valley in California is home to many of the world's largest technology companies.",
        "The Amazon River in Brazil was named because early explorers named a river after the legendary Amazons; the US has its own mighty rivers like the Mississippi.",
        "The US Library of Congress is the largest library in the world.",
    ],
    "Venezuela": [
        "Venezuela has the world's largest proven oil reserves.",
        "Angel Falls in Venezuela is the world's highest uninterrupted waterfall (979 m).",
        "Venezuela has won more Miss Universe and Miss World titles than any other country.",
        "Venezuela's tepui (table-top mountains) inspired Arthur Conan Doyle's 'The Lost World'.",
    ],
    "Vietnam": [
        "Vietnam is the world's second-largest exporter of coffee (after Brazil).",
        "Vietnam has a coastline of over 3,444 km along the South China Sea.",
        "Halong Bay in Vietnam is one of the New Seven Wonders of Nature.",
        "Vietnam is one of the fastest growing economies in Asia.",
        "The Mekong River Delta, often called the 'rice bowl' of Asia, is partly in Vietnam.",
    ],
}


# ─────────────────────────────────────────────
# Currency Code → { name, symbol }
# ─────────────────────────────────────────────
CURRENCY_CODES = {
    "AED": {"name": "UAE Dirham", "symbol": "د.إ"},
    "AFN": {"name": "Afghan Afghani", "symbol": "؋"},
    "ALL": {"name": "Albanian Lek", "symbol": "L"},
    "AMD": {"name": "Armenian Dram", "symbol": "֏"},
    "ANG": {"name": "Netherlands Antillean Guilder", "symbol": "ƒ"},
    "AOA": {"name": "Angolan Kwanza", "symbol": "Kz"},
    "ARS": {"name": "Argentine Peso", "symbol": "$"},
    "AUD": {"name": "Australian Dollar", "symbol": "A$"},
    "AWG": {"name": "Aruban Florin", "symbol": "ƒ"},
    "AZN": {"name": "Azerbaijani Manat", "symbol": "₼"},
    "BAM": {"name": "Bosnian Mark", "symbol": "KM"},
    "BBD": {"name": "Barbadian Dollar", "symbol": "$"},
    "BDT": {"name": "Bangladeshi Taka", "symbol": "৳"},
    "BGN": {"name": "Bulgarian Lev", "symbol": "лв"},
    "BHD": {"name": "Bahraini Dinar", "symbol": ".د.ب"},
    "BMD": {"name": "Bermudian Dollar", "symbol": "$"},
    "BND": {"name": "Brunei Dollar", "symbol": "$"},
    "BOB": {"name": "Bolivian Boliviano", "symbol": "Bs."},
    "BRL": {"name": "Brazilian Real", "symbol": "R$"},
    "BSD": {"name": "Bahamian Dollar", "symbol": "$"},
    "BTN": {"name": "Bhutanese Ngultrum", "symbol": "Nu"},
    "BWP": {"name": "Botswanan Pula", "symbol": "P"},
    "BYN": {"name": "Belarusian Ruble", "symbol": "Br"},
    "BZD": {"name": "Belize Dollar", "symbol": "BZ$"},
    "CAD": {"name": "Canadian Dollar", "symbol": "C$"},
    "CDF": {"name": "Congolese Franc", "symbol": "FC"},
    "CHF": {"name": "Swiss Franc", "symbol": "Fr"},
    "CLP": {"name": "Chilean Peso", "symbol": "$"},
    "CNY": {"name": "Chinese Yuan", "symbol": "¥"},
    "COP": {"name": "Colombian Peso", "symbol": "$"},
    "CRC": {"name": "Costa Rican Colón", "symbol": "₡"},
    "CUP": {"name": "Cuban Peso", "symbol": "$"},
    "CVE": {"name": "Cape Verdean Escudo", "symbol": "$"},
    "CZK": {"name": "Czech Koruna", "symbol": "Kč"},
    "DJF": {"name": "Djiboutian Franc", "symbol": "Fdj"},
    "DKK": {"name": "Danish Krone", "symbol": "kr"},
    "DOP": {"name": "Dominican Peso", "symbol": "RD$"},
    "DZD": {"name": "Algerian Dinar", "symbol": "دج"},
    "EGP": {"name": "Egyptian Pound", "symbol": "£"},
    "ERN": {"name": "Eritrean Nakfa", "symbol": "Nfk"},
    "ETB": {"name": "Ethiopian Birr", "symbol": "Br"},
    "EUR": {"name": "Euro", "symbol": "€"},
    "FJD": {"name": "Fijian Dollar", "symbol": "$"},
    "GBP": {"name": "British Pound", "symbol": "£"},
    "GEL": {"name": "Georgian Lari", "symbol": "₾"},
    "GHS": {"name": "Ghanaian Cedi", "symbol": "₵"},
    "GMD": {"name": "Gambian Dalasi", "symbol": "D"},
    "GNF": {"name": "Guinean Franc", "symbol": "FG"},
    "GTQ": {"name": "Guatemalan Quetzal", "symbol": "Q"},
    "GYD": {"name": "Guyanese Dollar", "symbol": "$"},
    "HKD": {"name": "Hong Kong Dollar", "symbol": "HK$"},
    "HNL": {"name": "Honduran Lempira", "symbol": "L"},
    "HRK": {"name": "Croatian Kuna", "symbol": "kn"},
    "HTG": {"name": "Haitian Gourde", "symbol": "G"},
    "HUF": {"name": "Hungarian Forint", "symbol": "Ft"},
    "IDR": {"name": "Indonesian Rupiah", "symbol": "Rp"},
    "ILS": {"name": "Israeli New Shekel", "symbol": "₪"},
    "INR": {"name": "Indian Rupee", "symbol": "₹"},
    "IQD": {"name": "Iraqi Dinar", "symbol": "ع.د"},
    "IRR": {"name": "Iranian Rial", "symbol": "﷼"},
    "ISK": {"name": "Icelandic Króna", "symbol": "kr"},
    "JMD": {"name": "Jamaican Dollar", "symbol": "$"},
    "JOD": {"name": "Jordanian Dinar", "symbol": "JD"},
    "JPY": {"name": "Japanese Yen", "symbol": "¥"},
    "KES": {"name": "Kenyan Shilling", "symbol": "KSh"},
    "KGS": {"name": "Kyrgyzstani Som", "symbol": "с"},
    "KHR": {"name": "Cambodian Riel", "symbol": "៛"},
    "KRW": {"name": "South Korean Won", "symbol": "₩"},
    "KWD": {"name": "Kuwaiti Dinar", "symbol": "د.ك"},
    "KZT": {"name": "Kazakhstani Tenge", "symbol": "₸"},
    "LAK": {"name": "Laotian Kip", "symbol": "₭"},
    "LBP": {"name": "Lebanese Pound", "symbol": "£"},
    "LKR": {"name": "Sri Lankan Rupee", "symbol": "₨"},
    "LYD": {"name": "Libyan Dinar", "symbol": "LD"},
    "MAD": {"name": "Moroccan Dirham", "symbol": "MAD"},
    "MDL": {"name": "Moldovan Leu", "symbol": "L"},
    "MKD": {"name": "Macedonian Denar", "symbol": "ден"},
    "MMK": {"name": "Myanmar Kyat", "symbol": "K"},
    "MNT": {"name": "Mongolian Tögrög", "symbol": "₮"},
    "MOP": {"name": "Macanese Pataca", "symbol": "P"},
    "MRU": {"name": "Mauritanian Ouguiya", "symbol": "UM"},
    "MUR": {"name": "Mauritian Rupee", "symbol": "₨"},
    "MVR": {"name": "Maldivian Rufiyaa", "symbol": "Rf"},
    "MWK": {"name": "Malawian Kwacha", "symbol": "MK"},
    "MXN": {"name": "Mexican Peso", "symbol": "$"},
    "MYR": {"name": "Malaysian Ringgit", "symbol": "RM"},
    "MZN": {"name": "Mozambican Metical", "symbol": "MT"},
    "NAD": {"name": "Namibian Dollar", "symbol": "$"},
    "NGN": {"name": "Nigerian Naira", "symbol": "₦"},
    "NIO": {"name": "Nicaraguan Córdoba", "symbol": "C$"},
    "NOK": {"name": "Norwegian Krone", "symbol": "kr"},
    "NPR": {"name": "Nepalese Rupee", "symbol": "₨"},
    "NZD": {"name": "New Zealand Dollar", "symbol": "NZ$"},
    "OMR": {"name": "Omani Rial", "symbol": "ر.ع."},
    "PAB": {"name": "Panamanian Balboa", "symbol": "B/."},
    "PEN": {"name": "Peruvian Sol", "symbol": "S/."},
    "PHP": {"name": "Philippine Peso", "symbol": "₱"},
    "PKR": {"name": "Pakistani Rupee", "symbol": "₨"},
    "PLN": {"name": "Polish Złoty", "symbol": "zł"},
    "PYG": {"name": "Paraguayan Guaraní", "symbol": "₲"},
    "QAR": {"name": "Qatari Riyal", "symbol": "ر.ق"},
    "RON": {"name": "Romanian Leu", "symbol": "lei"},
    "RSD": {"name": "Serbian Dinar", "symbol": "din."},
    "RUB": {"name": "Russian Ruble", "symbol": "₽"},
    "RWF": {"name": "Rwandan Franc", "symbol": "Fr"},
    "SAR": {"name": "Saudi Riyal", "symbol": "ر.س"},
    "SDG": {"name": "Sudanese Pound", "symbol": "ج.س."},
    "SEK": {"name": "Swedish Krona", "symbol": "kr"},
    "SGD": {"name": "Singapore Dollar", "symbol": "S$"},
    "SOS": {"name": "Somali Shilling", "symbol": "Sh"},
    "SYP": {"name": "Syrian Pound", "symbol": "£"},
    "THB": {"name": "Thai Baht", "symbol": "฿"},
    "TJS": {"name": "Tajikistani Somoni", "symbol": "SM"},
    "TMT": {"name": "Turkmenistani Manat", "symbol": "T"},
    "TND": {"name": "Tunisian Dinar", "symbol": "د.ت"},
    "TRY": {"name": "Turkish Lira", "symbol": "₺"},
    "TTD": {"name": "Trinidad and Tobago Dollar", "symbol": "TT$"},
    "TWD": {"name": "New Taiwan Dollar", "symbol": "NT$"},
    "TZS": {"name": "Tanzanian Shilling", "symbol": "Sh"},
    "UAH": {"name": "Ukrainian Hryvnia", "symbol": "₴"},
    "UGX": {"name": "Ugandan Shilling", "symbol": "Sh"},
    "USD": {"name": "US Dollar", "symbol": "$"},
    "UYU": {"name": "Uruguayan Peso", "symbol": "$U"},
    "UZS": {"name": "Uzbekistani Som", "symbol": "so'm"},
    "VES": {"name": "Venezuelan Bolívar", "symbol": "Bs.S"},
    "VND": {"name": "Vietnamese Đồng", "symbol": "₫"},
    "XAF": {"name": "Central African CFA Franc", "symbol": "CFA"},
    "XOF": {"name": "West African CFA Franc", "symbol": "CFA"},
    "YER": {"name": "Yemeni Rial", "symbol": "﷼"},
    "ZAR": {"name": "South African Rand", "symbol": "R"},
    "ZMW": {"name": "Zambian Kwacha", "symbol": "ZK"},
    "ZWL": {"name": "Zimbabwean Dollar", "symbol": "Z$"},
}

# ──────────────────────────────────────────────
#  WORLD_RECORDS  –  Global Geographical & Political Records
# ──────────────────────────────────────────────
WORLD_RECORDS = {

    # ── Geographical ──────────────────────────
    "largest_by_area": [
        {"rank": 1,  "country": "Russia",           "value": "17,098,242", "unit": "km²", "alpha2": "ru"},
        {"rank": 2,  "country": "Canada",            "value": "9,984,670",  "unit": "km²", "alpha2": "ca"},
        {"rank": 3,  "country": "United States",     "value": "9,833,517",  "unit": "km²", "alpha2": "us"},
        {"rank": 4,  "country": "China",             "value": "9,596,960",  "unit": "km²", "alpha2": "cn"},
        {"rank": 5,  "country": "Brazil",            "value": "8,515,767",  "unit": "km²", "alpha2": "br"},
        {"rank": 6,  "country": "Australia",         "value": "7,741,220",  "unit": "km²", "alpha2": "au"},
        {"rank": 7,  "country": "India",             "value": "3,287,263",  "unit": "km²", "alpha2": "in"},
        {"rank": 8,  "country": "Argentina",         "value": "2,780,400",  "unit": "km²", "alpha2": "ar"},
        {"rank": 9,  "country": "Kazakhstan",        "value": "2,724,900",  "unit": "km²", "alpha2": "kz"},
        {"rank": 10, "country": "Algeria",           "value": "2,381,741",  "unit": "km²", "alpha2": "dz"},
    ],

    "smallest_by_area": [
        {"rank": 1, "country": "Vatican City",       "value": "0.44",   "unit": "km²", "alpha2": "va"},
        {"rank": 2, "country": "Monaco",             "value": "2.02",   "unit": "km²", "alpha2": "mc"},
        {"rank": 3, "country": "San Marino",         "value": "61",     "unit": "km²", "alpha2": "sm"},
        {"rank": 4, "country": "Liechtenstein",      "value": "160",    "unit": "km²", "alpha2": "li"},
        {"rank": 5, "country": "Malta",              "value": "316",    "unit": "km²", "alpha2": "mt"},
    ],

    "most_populous": [
        {"rank": 1,  "country": "India",             "value": "1,441,719,852", "unit": "people", "alpha2": "in"},
        {"rank": 2,  "country": "China",             "value": "1,409,670,000", "unit": "people", "alpha2": "cn"},
        {"rank": 3,  "country": "United States",     "value": "339,996,563",   "unit": "people", "alpha2": "us"},
        {"rank": 4,  "country": "Indonesia",         "value": "277,534,122",   "unit": "people", "alpha2": "id"},
        {"rank": 5,  "country": "Pakistan",          "value": "231,402,117",   "unit": "people", "alpha2": "pk"},
        {"rank": 6,  "country": "Brazil",            "value": "216,422,446",   "unit": "people", "alpha2": "br"},
        {"rank": 7,  "country": "Nigeria",           "value": "223,804,632",   "unit": "people", "alpha2": "ng"},
        {"rank": 8,  "country": "Bangladesh",        "value": "170,000,000",   "unit": "people", "alpha2": "bd"},
        {"rank": 9,  "country": "Russia",            "value": "144,444,359",   "unit": "people", "alpha2": "ru"},
        {"rank": 10, "country": "Ethiopia",          "value": "126,527,060",   "unit": "people", "alpha2": "et"},
    ],

    "highest_mountains": [
        {"rank": 1,  "peak": "Mount Everest",        "country": "Nepal / China",    "value": "8,849", "unit": "m asl", "alpha2": "np"},
        {"rank": 2,  "peak": "K2",                   "country": "Pakistan / China", "value": "8,611", "unit": "m asl", "alpha2": "pk"},
        {"rank": 3,  "peak": "Kangchenjunga",        "country": "Nepal / India",    "value": "8,586", "unit": "m asl", "alpha2": "np"},
        {"rank": 4,  "peak": "Lhotse",               "country": "Nepal / China",    "value": "8,516", "unit": "m asl", "alpha2": "np"},
        {"rank": 5,  "peak": "Makalu",               "country": "Nepal / China",    "value": "8,485", "unit": "m asl", "alpha2": "np"},
        {"rank": 6,  "peak": "Cho Oyu",              "country": "Nepal / China",    "value": "8,188", "unit": "m asl", "alpha2": "np"},
        {"rank": 7,  "peak": "Dhaulagiri I",         "country": "Nepal",            "value": "8,167", "unit": "m asl", "alpha2": "np"},
        {"rank": 8,  "peak": "Manaslu",              "country": "Nepal",            "value": "8,163", "unit": "m asl", "alpha2": "np"},
        {"rank": 9,  "peak": "Nanga Parbat",         "country": "Pakistan",         "value": "8,126", "unit": "m asl", "alpha2": "pk"},
        {"rank": 10, "peak": "Annapurna I",          "country": "Nepal",            "value": "8,091", "unit": "m asl", "alpha2": "np"},
    ],

    "longest_rivers": [
        {"rank": 1,  "river": "Nile",       "countries": "Egypt / Sudan / Uganda", "value": "6,650",  "unit": "km", "alpha2": "eg"},
        {"rank": 2,  "river": "Amazon",     "countries": "Brazil / Peru / Colombia","value": "6,400", "unit": "km", "alpha2": "br"},
        {"rank": 3,  "river": "Yangtze",    "countries": "China",                  "value": "6,300",  "unit": "km", "alpha2": "cn"},
        {"rank": 4,  "river": "Mississippi","countries": "United States",          "value": "6,275",  "unit": "km", "alpha2": "us"},
        {"rank": 5,  "river": "Yenisei",    "countries": "Russia / Mongolia",      "value": "5,539",  "unit": "km", "alpha2": "ru"},
        {"rank": 6,  "river": "Yellow River","countries": "China",                 "value": "5,464",  "unit": "km", "alpha2": "cn"},
        {"rank": 7,  "river": "Ob",         "countries": "Russia / Kazakhstan",    "value": "5,410",  "unit": "km", "alpha2": "ru"},
        {"rank": 8,  "river": "Congo",      "countries": "DR Congo / Congo",       "value": "4,700",  "unit": "km", "alpha2": "cd"},
        {"rank": 9,  "river": "Amur",       "countries": "Russia / China",         "value": "4,444",  "unit": "km", "alpha2": "ru"},
        {"rank": 10, "river": "Lena",       "countries": "Russia",                 "value": "4,400",  "unit": "km", "alpha2": "ru"},
    ],

    "longest_coastlines": [
        {"rank": 1,  "country": "Canada",            "value": "202,080", "unit": "km", "alpha2": "ca"},
        {"rank": 2,  "country": "Norway",            "value": "58,133",  "unit": "km", "alpha2": "no"},
        {"rank": 3,  "country": "Indonesia",         "value": "54,716",  "unit": "km", "alpha2": "id"},
        {"rank": 4,  "country": "Russia",            "value": "37,653",  "unit": "km", "alpha2": "ru"},
        {"rank": 5,  "country": "Philippines",       "value": "36,289",  "unit": "km", "alpha2": "ph"},
        {"rank": 6,  "country": "Japan",             "value": "29,751",  "unit": "km", "alpha2": "jp"},
        {"rank": 7,  "country": "Australia",         "value": "25,760",  "unit": "km", "alpha2": "au"},
        {"rank": 8,  "country": "United States",     "value": "19,924",  "unit": "km", "alpha2": "us"},
        {"rank": 9,  "country": "Antarctica",        "value": "17,968",  "unit": "km", "alpha2": "aq"},
        {"rank": 10, "country": "New Zealand",       "value": "15,134",  "unit": "km", "alpha2": "nz"},
    ],

    # ── Political / Cultural ──────────────────
    "population_density": [
        {"rank": 1, "country": "Monaco",             "value": "26,150", "unit": "people/km²", "alpha2": "mc"},
        {"rank": 2, "country": "Singapore",          "value": "8,358",  "unit": "people/km²", "alpha2": "sg"},
        {"rank": 3, "country": "Bahrain",            "value": "2,239",  "unit": "people/km²", "alpha2": "bh"},
        {"rank": 4, "country": "Bangladesh",         "value": "1,265",  "unit": "people/km²", "alpha2": "bd"},
        {"rank": 5, "country": "Maldives",           "value": "1,802",  "unit": "people/km²", "alpha2": "mv"},
    ],

    "most_official_languages": [
        {"rank": 1,  "country": "Bolivia",       "value": "37", "unit": "official languages", "alpha2": "bo"},
        {"rank": 2,  "country": "Zimbabwe",      "value": "16", "unit": "official languages", "alpha2": "zw"},
        {"rank": 3,  "country": "South Africa",  "value": "11", "unit": "official languages", "alpha2": "za"},
        {"rank": 4,  "country": "Rwanda",        "value": "4",  "unit": "official languages", "alpha2": "rw"},
        {"rank": 5,  "country": "Singapore",     "value": "4",  "unit": "official languages", "alpha2": "sg"},
        {"rank": 6,  "country": "Switzerland",   "value": "4",  "unit": "official languages", "alpha2": "ch"},
        {"rank": 7,  "country": "Luxembourg",    "value": "3",  "unit": "official languages", "alpha2": "lu"},
        {"rank": 8,  "country": "Belgium",       "value": "3",  "unit": "official languages", "alpha2": "be"},
        {"rank": 9,  "country": "New Zealand",   "value": "3",  "unit": "official languages", "alpha2": "nz"},
        {"rank": 10, "country": "Canada",        "value": "2",  "unit": "official languages", "alpha2": "ca"},
    ],

    "most_timezones": [
        {"rank": 1,  "country": "France",          "value": "12", "unit": "time zones (incl. overseas)",      "alpha2": "fr"},
        {"rank": 2,  "country": "Russia",          "value": "11", "unit": "time zones",                      "alpha2": "ru"},
        {"rank": 3,  "country": "United States",   "value": "11", "unit": "time zones (incl. territories)", "alpha2": "us"},
        {"rank": 4,  "country": "Australia",       "value": "8",  "unit": "time zones",                      "alpha2": "au"},
        {"rank": 5,  "country": "Canada",          "value": "6",  "unit": "time zones",                      "alpha2": "ca"},
        {"rank": 6,  "country": "United Kingdom",  "value": "5",  "unit": "time zones (incl. territories)", "alpha2": "gb"},
        {"rank": 7,  "country": "New Zealand",     "value": "5",  "unit": "time zones (incl. territories)", "alpha2": "nz"},
        {"rank": 8,  "country": "Brazil",          "value": "4",  "unit": "time zones",                      "alpha2": "br"},
        {"rank": 9,  "country": "Mexico",          "value": "4",  "unit": "time zones",                      "alpha2": "mx"},
        {"rank": 10, "country": "Indonesia",       "value": "3",  "unit": "time zones",                      "alpha2": "id"},
    ],

    "notable_natural_records": [
        {"icon": "fa-thermometer-full",  "color": "#ef4444", "title": "Hottest Recorded Temp",
         "value": "56.7 °C (134 °F)",       "detail": "Death Valley, USA — July 10, 1913"},
        {"icon": "fa-thermometer-empty", "color": "#3b82f6", "title": "Coldest Recorded Temp",
         "value": "−89.2 °C (−128.6 °F)",   "detail": "Vostok Station, Antarctica — July 21, 1983"},
        {"icon": "fa-water",             "color": "#06b6d4", "title": "Deepest Lake",
         "value": "1,642 m",                "detail": "Lake Baikal, Russia"},
        {"icon": "fa-arrow-down",        "color": "#8b5cf6", "title": "Deepest Ocean Trench",
         "value": "10,994 m",               "detail": "Mariana Trench, Pacific Ocean"},
        {"icon": "fa-tint",              "color": "#10b981", "title": "Largest Freshwater Lake",
         "value": "82,414 km²",             "detail": "Lake Superior, USA / Canada"},
        {"icon": "fa-cloud-rain",        "color": "#6366f1", "title": "Wettest Place on Earth",
         "value": "11,871 mm/yr",            "detail": "Mawsynram, Meghalaya, India"},
        {"icon": "fa-sun",               "color": "#f59e0b", "title": "Driest Place on Earth",
         "value": "< 0.1 mm/yr",            "detail": "Atacama Desert, Chile"},
        {"icon": "fa-anchor",            "color": "#0ea5e9", "title": "Largest Ocean",
         "value": "165.25 million km²",     "detail": "Pacific Ocean"},
        {"icon": "fa-globe-asia",        "color": "#14b8a6", "title": "Longest Mountain Range",
         "value": "7,000 km",               "detail": "Andes, South America"},
        {"icon": "fa-wind",              "color": "#a3a3a3", "title": "Largest Hot Desert",
         "value": "9.2 million km²",        "detail": "Sahara Desert, Africa"},
    ],

    "notable_manmade_records": [
        {"icon": "fa-building",          "color": "#ec4899", "title": "Tallest Building",
         "value": "828 m",                "detail": "Burj Khalifa, Dubai, UAE"},
        {"icon": "fa-long-arrow-alt-right", "color": "#f97316", "title": "Longest Wall",
         "value": "21,196 km",            "detail": "Great Wall of China"},
        {"icon": "fa-road",              "color": "#84cc16", "title": "Longest Bridge",
         "value": "164.8 km",             "detail": "Danyang-Kunshan Grand Bridge, China"},
        {"icon": "fa-subway",            "color": "#6366f1", "title": "Longest Rail Tunnel",
         "value": "57.1 km",              "detail": "Gotthard Base Tunnel, Switzerland"},
        {"icon": "fa-users",             "color": "#0d9488", "title": "Largest Stadium",
         "value": "114,000 seats",        "detail": "Rungrado May Day Stadium, North Korea"},
        {"icon": "fa-water",             "color": "#0ea5e9", "title": "Largest Dam (Volume)",
         "value": "39.3 billion m³",      "detail": "Kariba Dam, Zambia / Zimbabwe"},
        {"icon": "fa-male",              "color": "#f59e0b", "title": "Tallest Statue",
         "value": "182 m",                "detail": "Statue of Unity, Gujarat, India"},
        {"icon": "fa-plane",             "color": "#8b5cf6", "title": "Largest Airport (Area)",
         "value": "776 km²",              "detail": "King Fahd Int'l Airport, Saudi Arabia"},
        {"icon": "fa-hammer",            "color": "#ef4444", "title": "Deepest Mine",
         "value": "4 km deep",            "detail": "Mponeng Gold Mine, South Africa"},
        {"icon": "fa-route",             "color": "#10b981", "title": "Longest Highway",
         "value": "30,000+ km",           "detail": "Pan-American Highway, Americas"},
    ],
}

# ──────────────────────────────────────────────
#  COUNTRY_EXTRA_DATA  –  Economic & Military metrics
#  Sources: World Bank, IMF, UNDP, Global Firepower 2024
#
#  Keys:
#    gdp_billion    – Nominal GDP (USD billions, 2024 est.)
#    gdp_per_capita – GDP per capita (USD, 2024 est.)
#    hdi            – Human Development Index (UNDP 2022, 0–1 scale)
#    hdi_rank       – Global HDI rank
#    gini           – Gini coefficient (0 = perfect equality, 100 = max inequality)
#    unemployment   – Unemployment rate (%)
#    inflation      – CPI inflation rate (%, 2023)
#    military_active   – Active military personnel (thousands)
#    military_reserve  – Reserve personnel (thousands)
#    military_budget   – Defence budget (USD billions, 2024 est.)
#    gfp_rank          – Global Firepower index rank (2024, 1 = strongest)
# ──────────────────────────────────────────────
COUNTRY_EXTRA_DATA = {
    "United States Of America": {
        "gdp_billion": 28781, "gdp_per_capita": 85373,
        "hdi": 0.927, "hdi_rank": 20, "gini": 39.8,
        "unemployment": 3.7, "inflation": 3.4,
        "military_active": 1328, "military_reserve": 799,
        "military_budget": 886, "gfp_rank": 1,
    },
    "Russia": {
        "gdp_billion": 2021, "gdp_per_capita": 14403,
        "hdi": 0.821, "hdi_rank": 52, "gini": 36.0,
        "unemployment": 3.2, "inflation": 7.4,
        "military_active": 1320, "military_reserve": 2000,
        "military_budget": 109, "gfp_rank": 2,
    },
    "China": {
        "gdp_billion": 18533, "gdp_per_capita": 13136,
        "hdi": 0.788, "hdi_rank": 75, "gini": 38.2,
        "unemployment": 5.2, "inflation": 0.7,
        "military_active": 2035, "military_reserve": 510,
        "military_budget": 225, "gfp_rank": 3,
    },
    "India": {
        "gdp_billion": 3937, "gdp_per_capita": 2731,
        "hdi": 0.644, "hdi_rank": 134, "gini": 35.7,
        "unemployment": 7.8, "inflation": 5.7,
        "military_active": 1455, "military_reserve": 1155,
        "military_budget": 83, "gfp_rank": 4,
    },
    "United Kingdom": {
        "gdp_billion": 3495, "gdp_per_capita": 51075,
        "hdi": 0.940, "hdi_rank": 15, "gini": 35.1,
        "unemployment": 4.2, "inflation": 7.3,
        "military_active": 150, "military_reserve": 80,
        "military_budget": 74, "gfp_rank": 5,
    },
    "South Korea": {
        "gdp_billion": 1713, "gdp_per_capita": 33152,
        "hdi": 0.929, "hdi_rank": 19, "gini": 31.4,
        "unemployment": 2.7, "inflation": 3.6,
        "military_active": 555, "military_reserve": 3100,
        "military_budget": 50, "gfp_rank": 6,
    },
    "Pakistan": {
        "gdp_billion": 338, "gdp_per_capita": 1400,
        "hdi": 0.544, "hdi_rank": 164, "gini": 31.6,
        "unemployment": 6.3, "inflation": 29.2,
        "military_active": 654, "military_reserve": 500,
        "military_budget": 10, "gfp_rank": 7,
    },
    "Japan": {
        "gdp_billion": 4213, "gdp_per_capita": 33950,
        "hdi": 0.920, "hdi_rank": 24, "gini": 32.9,
        "unemployment": 2.5, "inflation": 3.3,
        "military_active": 247, "military_reserve": 56,
        "military_budget": 50, "gfp_rank": 8,
    },
    "France": {
        "gdp_billion": 3031, "gdp_per_capita": 46315,
        "hdi": 0.910, "hdi_rank": 28, "gini": 31.5,
        "unemployment": 7.1, "inflation": 4.9,
        "military_active": 204, "military_reserve": 36,
        "military_budget": 60, "gfp_rank": 9,
    },
    "Italy": {
        "gdp_billion": 2255, "gdp_per_capita": 38469,
        "hdi": 0.906, "hdi_rank": 30, "gini": 34.8,
        "unemployment": 6.1, "inflation": 6.0,
        "military_active": 165, "military_reserve": 19,
        "military_budget": 35, "gfp_rank": 10,
    },
    "Germany": {
        "gdp_billion": 4456, "gdp_per_capita": 53298,
        "hdi": 0.942, "hdi_rank": 9, "gini": 31.7,
        "unemployment": 3.1, "inflation": 6.0,
        "military_active": 183, "military_reserve": 30,
        "military_budget": 67, "gfp_rank": 19,
    },
    "Brazil": {
        "gdp_billion": 2331, "gdp_per_capita": 10784,
        "hdi": 0.760, "hdi_rank": 89, "gini": 52.9,
        "unemployment": 7.8, "inflation": 4.6,
        "military_active": 365, "military_reserve": 1340,
        "military_budget": 21, "gfp_rank": 13,
    },
    "Ukraine": {
        "gdp_billion": 178, "gdp_per_capita": 5363,
        "hdi": 0.773, "hdi_rank": 80, "gini": 26.6,
        "unemployment": 19.1, "inflation": 12.9,
        "military_active": 500, "military_reserve": 1000,
        "military_budget": 35, "gfp_rank": 18,
    },
    "Turkey": {
        "gdp_billion": 1108, "gdp_per_capita": 13043,
        "hdi": 0.838, "hdi_rank": 45, "gini": 41.9,
        "unemployment": 8.5, "inflation": 65.0,
        "military_active": 355, "military_reserve": 380,
        "military_budget": 15, "gfp_rank": 11,
    },
    "Iran": {
        "gdp_billion": 367, "gdp_per_capita": 4214,
        "hdi": 0.774, "hdi_rank": 78, "gini": 40.9,
        "unemployment": 9.0, "inflation": 45.0,
        "military_active": 610, "military_reserve": 350,
        "military_budget": 10, "gfp_rank": 14,
    },
    "Egypt": {
        "gdp_billion": 395, "gdp_per_capita": 3622,
        "hdi": 0.728, "hdi_rank": 104, "gini": 31.5,
        "unemployment": 7.5, "inflation": 34.0,
        "military_active": 438, "military_reserve": 479,
        "military_budget": 4, "gfp_rank": 15,
    },
    "Australia": {
        "gdp_billion": 1693, "gdp_per_capita": 64966,
        "hdi": 0.946, "hdi_rank": 10, "gini": 34.3,
        "unemployment": 3.7, "inflation": 5.6,
        "military_active": 59, "military_reserve": 27,
        "military_budget": 36, "gfp_rank": 16,
    },
    "Israel": {
        "gdp_billion": 564, "gdp_per_capita": 58270,
        "hdi": 0.919, "hdi_rank": 22, "gini": 38.8,
        "unemployment": 3.8, "inflation": 4.2,
        "military_active": 170, "military_reserve": 465,
        "military_budget": 24, "gfp_rank": 17,
    },
    "Canada": {
        "gdp_billion": 2242, "gdp_per_capita": 56793,
        "hdi": 0.935, "hdi_rank": 18, "gini": 33.3,
        "unemployment": 5.4, "inflation": 3.6,
        "military_active": 68, "military_reserve": 27,
        "military_budget": 24, "gfp_rank": 27,
    },
    "Spain": {
        "gdp_billion": 1582, "gdp_per_capita": 33231,
        "hdi": 0.911, "hdi_rank": 27, "gini": 34.7,
        "unemployment": 11.6, "inflation": 3.5,
        "military_active": 120, "military_reserve": 15,
        "military_budget": 12, "gfp_rank": 23,
    },
    "Netherlands": {
        "gdp_billion": 1118, "gdp_per_capita": 63754,
        "hdi": 0.946, "hdi_rank": 10, "gini": 28.2,
        "unemployment": 3.6, "inflation": 4.1,
        "military_active": 41, "military_reserve": 5,
        "military_budget": 12, "gfp_rank": 37,
    },
    "Poland": {
        "gdp_billion": 844, "gdp_per_capita": 22124,
        "hdi": 0.876, "hdi_rank": 35, "gini": 28.8,
        "unemployment": 2.9, "inflation": 11.4,
        "military_active": 216, "military_reserve": 75,
        "military_budget": 21, "gfp_rank": 21,
    },
    "Saudi Arabia": {
        "gdp_billion": 1091, "gdp_per_capita": 30436,
        "hdi": 0.875, "hdi_rank": 40, "gini": 45.9,
        "unemployment": 5.5, "inflation": 2.2,
        "military_active": 257, "military_reserve": 25,
        "military_budget": 76, "gfp_rank": 22,
    },
    "Argentina": {
        "gdp_billion": 621, "gdp_per_capita": 13370,
        "hdi": 0.842, "hdi_rank": 48, "gini": 42.3,
        "unemployment": 6.2, "inflation": 143.0,
        "military_active": 74, "military_reserve": 0,
        "military_budget": 2, "gfp_rank": 28,
    },
    "Indonesia": {
        "gdp_billion": 1371, "gdp_per_capita": 4942,
        "hdi": 0.713, "hdi_rank": 112, "gini": 38.2,
        "unemployment": 5.3, "inflation": 3.7,
        "military_active": 396, "military_reserve": 400,
        "military_budget": 9, "gfp_rank": 12,
    },
    "Mexico": {
        "gdp_billion": 1788, "gdp_per_capita": 13926,
        "hdi": 0.781, "hdi_rank": 74, "gini": 45.4,
        "unemployment": 2.8, "inflation": 4.7,
        "military_active": 277, "military_reserve": 82,
        "military_budget": 12, "gfp_rank": 30,
    },
    "Nigeria": {
        "gdp_billion": 253, "gdp_per_capita": 1072,
        "hdi": 0.535, "hdi_rank": 163, "gini": 35.1,
        "unemployment": 5.0, "inflation": 28.9,
        "military_active": 135, "military_reserve": 32,
        "military_budget": 3, "gfp_rank": 36,
    },
    "South Africa": {
        "gdp_billion": 405, "gdp_per_capita": 6766,
        "hdi": 0.717, "hdi_rank": 109, "gini": 63.0,
        "unemployment": 32.9, "inflation": 5.9,
        "military_active": 79, "military_reserve": 15,
        "military_budget": 3, "gfp_rank": 35,
    },
    "Sweden": {
        "gdp_billion": 593, "gdp_per_capita": 56197,
        "hdi": 0.952, "hdi_rank": 7, "gini": 27.6,
        "unemployment": 8.5, "inflation": 8.6,
        "military_active": 24, "military_reserve": 32,
        "military_budget": 8, "gfp_rank": 25,
    },
    "Norway": {
        "gdp_billion": 546, "gdp_per_capita": 99267,
        "hdi": 0.966, "hdi_rank": 2, "gini": 26.1,
        "unemployment": 1.8, "inflation": 5.5,
        "military_active": 24, "military_reserve": 45,
        "military_budget": 9, "gfp_rank": 50,
    },
    "Switzerland": {
        "gdp_billion": 884, "gdp_per_capita": 101994,
        "hdi": 0.962, "hdi_rank": 3, "gini": 33.1,
        "unemployment": 2.1, "inflation": 2.1,
        "military_active": 21, "military_reserve": 150,
        "military_budget": 6, "gfp_rank": 22,
    },
    "Singapore": {
        "gdp_billion": 467, "gdp_per_capita": 88447,
        "hdi": 0.939, "hdi_rank": 9, "gini": 45.9,
        "unemployment": 2.1, "inflation": 4.8,
        "military_active": 72, "military_reserve": 313,
        "military_budget": 13, "gfp_rank": 28,
    },
    "Thailand": {
        "gdp_billion": 576, "gdp_per_capita": 8246,
        "hdi": 0.803, "hdi_rank": 66, "gini": 36.4,
        "unemployment": 1.1, "inflation": 1.2,
        "military_active": 361, "military_reserve": 200,
        "military_budget": 8, "gfp_rank": 26,
    },
    "Vietnam": {
        "gdp_billion": 433, "gdp_per_capita": 4316,
        "hdi": 0.726, "hdi_rank": 107, "gini": 35.7,
        "unemployment": 2.3, "inflation": 3.3,
        "military_active": 482, "military_reserve": 5000,
        "military_budget": 7, "gfp_rank": 22,
    },
    "Philippines": {
        "gdp_billion": 437, "gdp_per_capita": 3860,
        "hdi": 0.710, "hdi_rank": 113, "gini": 40.7,
        "unemployment": 4.4, "inflation": 6.0,
        "military_active": 143, "military_reserve": 131,
        "military_budget": 4, "gfp_rank": 40,
    },
    "Malaysia": {
        "gdp_billion": 430, "gdp_per_capita": 12613,
        "hdi": 0.807, "hdi_rank": 62, "gini": 40.7,
        "unemployment": 3.5, "inflation": 2.5,
        "military_active": 113, "military_reserve": 51,
        "military_budget": 4, "gfp_rank": 44,
    },
    "Bangladesh": {
        "gdp_billion": 460, "gdp_per_capita": 2668,
        "hdi": 0.661, "hdi_rank": 129, "gini": 32.4,
        "unemployment": 5.1, "inflation": 9.0,
        "military_active": 163, "military_reserve": 50,
        "military_budget": 5, "gfp_rank": 39,
    },
    "Ethiopia": {
        "gdp_billion": 205, "gdp_per_capita": 1617,
        "hdi": 0.492, "hdi_rank": 174, "gini": 35.0,
        "unemployment": 3.5, "inflation": 33.9,
        "military_active": 138, "military_reserve": 0,
        "military_budget": 1, "gfp_rank": 60,
    },
    "Morocco": {
        "gdp_billion": 142, "gdp_per_capita": 3749,
        "hdi": 0.698, "hdi_rank": 123, "gini": 39.5,
        "unemployment": 11.8, "inflation": 6.1,
        "military_active": 196, "military_reserve": 150,
        "military_budget": 5, "gfp_rank": 47,
    },
    "Algeria": {
        "gdp_billion": 239, "gdp_per_capita": 5264,
        "hdi": 0.745, "hdi_rank": 91, "gini": 27.6,
        "unemployment": 11.8, "inflation": 9.3,
        "military_active": 130, "military_reserve": 150,
        "military_budget": 9, "gfp_rank": 31,
    },
    "New Zealand": {
        "gdp_billion": 253, "gdp_per_capita": 48781,
        "hdi": 0.939, "hdi_rank": 13, "gini": 33.0,
        "unemployment": 3.9, "inflation": 5.7,
        "military_active": 9, "military_reserve": 9,
        "military_budget": 4, "gfp_rank": 73,
    },
    "Finland": {
        "gdp_billion": 305, "gdp_per_capita": 55102,
        "hdi": 0.940, "hdi_rank": 12, "gini": 27.4,
        "unemployment": 7.6, "inflation": 4.3,
        "military_active": 21, "military_reserve": 280,
        "military_budget": 6, "gfp_rank": 54,
    },
    "Chile": {
        "gdp_billion": 335, "gdp_per_capita": 17064,
        "hdi": 0.860, "hdi_rank": 44, "gini": 44.9,
        "unemployment": 8.6, "inflation": 7.6,
        "military_active": 80, "military_reserve": 40,
        "military_budget": 6, "gfp_rank": 55,
    },
    "Colombia": {
        "gdp_billion": 363, "gdp_per_capita": 7068,
        "hdi": 0.758, "hdi_rank": 91, "gini": 54.2,
        "unemployment": 10.2, "inflation": 11.7,
        "military_active": 293, "military_reserve": 62,
        "military_budget": 5, "gfp_rank": 33,
    },
    "Peru": {
        "gdp_billion": 268, "gdp_per_capita": 7878,
        "hdi": 0.762, "hdi_rank": 87, "gini": 40.2,
        "unemployment": 6.6, "inflation": 7.9,
        "military_active": 80, "military_reserve": 188,
        "military_budget": 4, "gfp_rank": 51,
    },
    "Greece": {
        "gdp_billion": 239, "gdp_per_capita": 21903,
        "hdi": 0.887, "hdi_rank": 33, "gini": 30.0,
        "unemployment": 11.1, "inflation": 4.2,
        "military_active": 141, "military_reserve": 221,
        "military_budget": 8, "gfp_rank": 30,
    },
    "Kenya": {
        "gdp_billion": 107, "gdp_per_capita": 2079,
        "hdi": 0.601, "hdi_rank": 152, "gini": 38.7,
        "unemployment": 5.4, "inflation": 6.8,
        "military_active": 24, "military_reserve": 0,
        "military_budget": 1, "gfp_rank": 81,
    },
    "Cuba": {
        "gdp_billion": 107, "gdp_per_capita": 9500,
        "hdi": 0.764, "hdi_rank": 83, "gini": 38.0,
        "unemployment": 1.3, "inflation": 39.0,
        "military_active": 49, "military_reserve": 39,
        "military_budget": 0, "gfp_rank": 54,
    },
    "Portugal": {
        "gdp_billion": 287, "gdp_per_capita": 27698,
        "hdi": 0.866, "hdi_rank": 38, "gini": 32.8,
        "unemployment": 6.5, "inflation": 5.3,
        "military_active": 27, "military_reserve": 212,
        "military_budget": 4, "gfp_rank": 48,
    },
    "Austria": {
        "gdp_billion": 526, "gdp_per_capita": 58015,
        "hdi": 0.916, "hdi_rank": 25, "gini": 30.8,
        "unemployment": 5.1, "inflation": 7.7,
        "military_active": 23, "military_reserve": 27,
        "military_budget": 3, "gfp_rank": 46,
    },
    "Belgium": {
        "gdp_billion": 622, "gdp_per_capita": 53267,
        "hdi": 0.937, "hdi_rank": 13, "gini": 27.2,
        "unemployment": 5.7, "inflation": 4.1,
        "military_active": 23, "military_reserve": 4,
        "military_budget": 6, "gfp_rank": 61,
    },
    "Denmark": {
        "gdp_billion": 404, "gdp_per_capita": 68008,
        "hdi": 0.952, "hdi_rank": 6, "gini": 28.8,
        "unemployment": 5.1, "inflation": 4.7,
        "military_active": 17, "military_reserve": 60,
        "military_budget": 6, "gfp_rank": 56,
    },
    "Iraq": {
        "gdp_billion": 268, "gdp_per_capita": 6316,
        "hdi": 0.686, "hdi_rank": 121, "gini": 29.5,
        "unemployment": 13.6, "inflation": 4.0,
        "military_active": 196, "military_reserve": 0,
        "military_budget": 7, "gfp_rank": 41,
    },
    "North Korea": {
        "gdp_billion": 18, "gdp_per_capita": 720,
        "hdi": 0.733, "hdi_rank": 0, "gini": 0,
        "unemployment": 0, "inflation": 0,
        "military_active": 1280, "military_reserve": 600,
        "military_budget": 4, "gfp_rank": 34,
    },
    "Venezuela": {
        "gdp_billion": 97, "gdp_per_capita": 3305,
        "hdi": 0.691, "hdi_rank": 120, "gini": 44.8,
        "unemployment": 7.0, "inflation": 400,
        "military_active": 150, "military_reserve": 8,
        "military_budget": 0, "gfp_rank": 58,
    },
    "Romania": {
        "gdp_billion": 351, "gdp_per_capita": 18446,
        "hdi": 0.821, "hdi_rank": 53, "gini": 34.9,
        "unemployment": 5.2, "inflation": 10.4,
        "military_active": 68, "military_reserve": 53,
        "military_budget": 6, "gfp_rank": 38,
    },
    "United Arab Emirates": {
        "gdp_billion": 527, "gdp_per_capita": 51108,
        "hdi": 0.911, "hdi_rank": 26, "gini": 32.5,
        "unemployment": 3.0, "inflation": 4.8,
        "military_active": 63, "military_reserve": 0,
        "military_budget": 23, "gfp_rank": 20,
    },
    "Czechia": {
        "gdp_billion": 340, "gdp_per_capita": 31612,
        "hdi": 0.900, "hdi_rank": 32, "gini": 25.3,
        "unemployment": 2.6, "inflation": 11.0,
        "military_active": 27, "military_reserve": 5,
        "military_budget": 4, "gfp_rank": 44,
    },
    "Hungary": {
        "gdp_billion": 213, "gdp_per_capita": 22050,
        "hdi": 0.851, "hdi_rank": 46, "gini": 29.9,
        "unemployment": 4.1, "inflation": 17.1,
        "military_active": 27, "military_reserve": 20,
        "military_budget": 3, "gfp_rank": 57,
    },
}


